<?php
// auto-generated by sfGeneratorConfigHandler
// date: 2009/04/06 04:24:30
require sfConfig::get('sf_symfony_lib_dir').'/plugins/sfCompat10Plugin/config/config.php';
require_once(sfConfig::get('sf_module_cache_dir').'/autoOferta/actions/actions.class.php');

