<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2009/04/06 04:26:04

return array(
'propel' => new sfPropelDatabase(array (
  'dsn' => 'mysql:dbname=infoteknia;host=localhost',
  'username' => 'root',
  'password' => 'root',
  'encoding' => 'utf8',
  'persistent' => true,
  'pooling' => true,
  'classname' => 'DebugPDO',
  'name' => 'propel',
)),);
