generator:
  class:              sfPropelAdminGenerator
  param:
    model_class:      Info
    theme:            default

    edit:
      title:    Editando  textos de las secciones

    fields:
      principal:
        params: >
          rich=true
          tinymce_options=height:200,
          width:650,
          language:'es',
          theme_advanced_buttons1:'bold,italic,underline,strikethrough,|,justifyleft,justifycenter,justifyright,justifyfull,|,undo,redo,|,cut,copy,paste,pastetext,pasteword,|,bullist,numlist,|,link,unlink',
          theme_advanced_buttons2:''

      secundario:
        params: >
          rich=true
          tinymce_options=height:200,
          width:650,
          language:'es',
          theme_advanced_buttons1:'bold,italic,underline,strikethrough,|,justifyleft,justifycenter,justifyright,justifyfull,|,undo,redo,|,cut,copy,paste,pastetext,pasteword,|,bullist,numlist,|,link,unlink',
          theme_advanced_buttons2:''
