dev:
  propel:
    param:
      classname: DebugPDO
test:
  propel:
    param:
      classname: DebugPDO

all:
  propel:
    class: sfPropelDatabase
    param:
      dsn:        mysql:dbname=infoteknia;host=localhost
      username:   root
      password:   root
      encoding:   utf8
      persistent: true
      pooling:    true
      classname:  PropelPDO

